/*
 * generated by Xtext
 */
package org.jjflyboy.tjpeditor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ProjectUiModule extends org.jjflyboy.tjpeditor.ui.AbstractProjectUiModule {
	public ProjectUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
