/*
* generated by Xtext
*/
package org.jjflyboy.tjpeditor.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.jjflyboy.tjpeditor.services.ProjectGrammarAccess;

public class ProjectParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ProjectGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.jjflyboy.tjpeditor.parser.antlr.internal.InternalProjectParser createParser(XtextTokenStream stream) {
		return new org.jjflyboy.tjpeditor.parser.antlr.internal.InternalProjectParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Global";
	}
	
	public ProjectGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ProjectGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
