/*
* generated by Xtext
*/
package org.jjflyboy.tjpeditor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ProjectAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/jjflyboy/tjpeditor/parser/antlr/internal/InternalProject.tokens");
	}
}
