/*
* generated by Xtext
*/
package org.jjflyboy.tjpeditor.ui.contentassist;

import org.jjflyboy.tjpeditor.ui.contentassist.AbstractProjectProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ProjectProposalProvider extends AbstractProjectProposalProvider {

}
