/*
* generated by Xtext
*/
package org.jjflyboy.tjpeditor;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ProjectUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.jjflyboy.tjpeditor.ui.internal.ProjectActivator.getInstance().getInjector("org.jjflyboy.tjpeditor.Project");
	}
	
}
