/*
 * generated by Xtext
 */
package org.jjflyboy.tjpeditor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProjectRuntimeModule extends org.jjflyboy.tjpeditor.AbstractProjectRuntimeModule {

}
